bindd = SUPER SHIFT ALT, SPACE, Omarchy menu, exec, omarchy-menu

unbind = ALT, SPACE
bindd = ALT, SPACE, ChatGPT, exec, ~/toggle-chatgpt.sh

bindd = SUPER SHIFT, Up, Move window to up monitor, movewindow, mon:+1
bindd = SUPER SHIFT, Down, Move window to down monitor, movewindow, mon:-1
bindd = CTRL, grave, Next app instance, cyclenext

unbind = SUPER ALT, Right
unbind = SUPER ALT, Left
bindd = SUPER ALT, Right, Next workspace, workspace, +1
bindd = SUPER ALT, Left, Prev workspace, workspace, -1

unbind = SUPER CTRL, B
bindd = SUPER, A, Bluetooth controls, exec, omarchy-launch-bluetooth