bindd = SUPER SHIFT ALT, SPACE, Omarchy menu, exec, omarchy-menu

unbind = ALT, SPACE
bindd = ALT, SPACE, ChatGPT, exec, ~/toggle-chatgpt.sh

bindd = SUPER SHIFT, Up, Move window up, movewindow, mon:+1
bindd = SUPER SHIFT, Down, Move window down, movewindow, mon:-1
bindd = CTRL, grave, Next app instance, cyclenext
