general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    col.inactive_border = 0x60757373
    col.active_border = 0xff0078d4
}

decoration {
    rounding = 0

    blur {
        size = 12
        passes = 3
        noise = 0.03
        vibrancy = 0.7
        vibrancy_darkness = 1
        contrast = 1.5
    }

    shadow {
      enabled = false
    }

    dim_inactive = true
    dim_strength = 0.3
}

# mako blur
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0.3, match:namespace notifications
