env = GDK_SCALE,1
monitor = HDMI-A-2, preferred,auto,auto
monitor = HDMI-A-1, preferred, auto, 1

workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-2
workspace = 3, monitor:HDMI-A-2
workspace = 4, monitor:HDMI-A-2
workspace = 5, monitor:HDMI-A-2
workspace = 6, monitor:HDMI-A-2

windowrule = match:class google-chrome, workspace 1, maximize on
windowrule = match:class jetbrains-webstorm, workspace 2
windowrule = match:class md.obsidian.Obsidian, workspace 3, maximize on
windowrule = match:class com.mitchellh.ghostty, workspace 5
windowrule = match:class org\.telegram.+, workspace 4
windowrule = match:class slack, workspace 4
windowrule = match:class discord, workspace 4
windowrule = match:class cursor, workspace 6

windowrule = match:class chrome-chatgpt.com__-Default, float on, max_size 800 600
windowrule = match:class jetbrains-webstorm, no_blur on, opacity 1 override
# focus on webstorm popups when hovering with mouse
windowrule = match:class jetbrains-webstorm, match:float 1, no_follow_mouse off

# blur walker
layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0.5, match:namespace walker

# style floating windows
windowrule = rounding 8, match:float 1
windowrule = border_size 1, match:float 1

# blur waybar
layerrule = blur on, match:namespace waybar