source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

background {
    monitor =
    path = ~/.config/omarchy/current/background
    blur_passes = 3
    contrast = 1.2
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 98
    font_family = Segoe UI Variable Semibold
    position = 0, -160
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date '+%A, %d %B')</span>"
    font_size = 22
    font_family = Segoe UI Variable Semibold
    position = 0, -328
    halign = center
    valign = top
}

input-field {
    monitor =
    size = 190, 36
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(60, 56, 54, 0.3)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = Segoe UI Variable Semibold
    placeholder_text = <span foreground="##ffffff99">Password</span>
    hide_input = false
    position = 0, 160
    halign = center
    valign = bottom
}

auth {
    fingerprint:enabled = false
}
